version: '3.8'

services:
  postgresql:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
       - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=leaderboardAdmin
      - POSTGRES_PASSWORD=19940913
      - POSTGRES_DB=local-leaderboard

volumes:
  postgres-data: