# Generated by Django 3.2.5 on 2021-07-02 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('flag', models.CharField(max_length=16)),
                ('url', models.URLField(default='')),
                ('complete', models.BooleanField(default=False)),
                ('complete_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
